apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.42
    path: "/mnt/Share/Share/nfs"