apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: container-test
    image: busybox
    args:
        - sleep
        - "1000"
    volumeMounts:
    - name: test
      mountPath: "/mnt"
      readOnly: true
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: pvc-nfs1
