apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: idf-build
spec:
  inputs:
    resources:
    - name: source
      type: git
#  outputs:
#    resources:
#    - name: image
  steps:
  - name: sleep
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - "sleep 36000"
#  - name: build-image
#    workingDir: /workspace/source
#    image: papawattu/build-firmware:latest
#    args: ["/workspace/source/phev-ttgo"]
#    securityContext:
#        runAsUser: 0
