apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-image-from-git-source-task-run
spec:
  taskRef:
    name: build-image-from-git-source
  inputs:
    resources:
      - name: idf-source
        resourceRef:
          name: ttgo-git